version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root  # 루트 사용자 비밀번호
            MYSQL_DATABASE: board         # 기본 데이터베이스 이름
            MYSQL_USER: user                   # 사용자 이름
            MYSQL_PASSWORD: user           # 사용자 비밀번호
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:

